/**
 * Portfolio Reporting Constants - Configuration values and constants
 * Part of the Portfolio Management domain within Turbo Asset IWMS
 */

// Report type constants
export const REPORT_TYPES = {
  PORTFOLIO_OVERVIEW: 'PORTFOLIO_OVERVIEW',
  FINANCIAL_SUMMARY: 'FINANCIAL_SUMMARY',
  LEASE_EXPIRATION: 'LEASE_EXPIRATION',
  OCCUPANCY_ANALYTICS: 'OCCUPANCY_ANALYTICS',
  MAINTENANCE_SUMMARY: 'MAINTENANCE_SUMMARY',
  EXECUTIVE_DASHBOARD: 'EXECUTIVE_DASHBOARD',
  CUSTOM: 'CUSTOM'
} as const;

// Alert priorities and categories
export const ALERT_PRIORITIES = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW'
} as const;

export const ALERT_CATEGORIES = {
  LEASE_EXPIRATION: 'LEASE_EXPIRATION',
  OCCUPANCY: 'OCCUPANCY',
  FINANCIAL: 'FINANCIAL',
  MAINTENANCE: 'MAINTENANCE',
  COMPLIANCE: 'COMPLIANCE',
  PERFORMANCE: 'PERFORMANCE',
  RISK: 'RISK',
  SYSTEM: 'SYSTEM'
} as const;

// Performance indicator thresholds
export const PERFORMANCE_THRESHOLDS = {
  OCCUPANCY_RATE: {
    EXCELLENT: 95,
    GOOD: 85,
    FAIR: 75,
    POOR: 65
  },
  FINANCIAL_EFFICIENCY: {
    EXCELLENT: 90,
    GOOD: 80,
    FAIR: 70,
    POOR: 60
  },
  MAINTENANCE_COMPLIANCE: {
    EXCELLENT: 98,
    GOOD: 90,
    FAIR: 80,
    POOR: 70
  }
} as const;

// Default configurations
export const DEFAULT_CONFIG = {
  DASHBOARD_REFRESH_INTERVAL: 300000, // 5 minutes
  MAX_CHART_DATA_POINTS: 1000,
  DEFAULT_PAGE_SIZE: 25,
  MAX_EXPORT_RECORDS: 100000,
  ALERT_RETENTION_DAYS: 90,
  REPORT_RETENTION_DAYS: 365,
  MAX_CONCURRENT_EXPORTS: 5,
  CACHE_TTL_SECONDS: 300,
  MAX_DASHBOARD_WIDGETS: 20,
  DEFAULT_TIMEFRAME: 'monthly'
} as const;