/**
 * Asset Management Constants - Configuration values and constants
 * Part of the Asset Management domain within Turbo Asset IWMS
 */

// Asset Status Constants
export const ASSET_STATUS = {
  OPERATIONAL: 'OPERATIONAL',
  DOWN: 'DOWN', 
  MAINTENANCE: 'MAINTENANCE',
  RETIRED: 'RETIRED',
  DISPOSED: 'DISPOSED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  IN_TRANSIT: 'IN_TRANSIT',
  STORAGE: 'STORAGE',
  TESTING: 'TESTING'
} as const;

// Asset Condition Constants
export const ASSET_CONDITION = {
  EXCELLENT: 'EXCELLENT',
  GOOD: 'GOOD',
  FAIR: 'FAIR', 
  POOR: 'POOR',
  CRITICAL: 'CRITICAL',
  NEW: 'NEW',
  REFURBISHED: 'REFURBISHED',
  UNKNOWN: 'UNKNOWN'
} as const;

// Asset Criticality Constants
export const ASSET_CRITICALITY = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW'
} as const;

// Depreciation Method Constants
export const DEPRECIATION_METHOD = {
  STRAIGHT_LINE: 'STRAIGHT_LINE',
  DECLINING_BALANCE: 'DECLINING_BALANCE',
  DOUBLE_DECLINING_BALANCE: 'DOUBLE_DECLINING_BALANCE',
  SUM_OF_YEARS_DIGITS: 'SUM_OF_YEARS_DIGITS',
  UNITS_OF_PRODUCTION: 'UNITS_OF_PRODUCTION'
} as const;

// Work Order Type Constants
export const WORK_ORDER_TYPE = {
  PREVENTIVE: 'PREVENTIVE',
  CORRECTIVE: 'CORRECTIVE',
  EMERGENCY: 'EMERGENCY',
  INSPECTION: 'INSPECTION',
  CALIBRATION: 'CALIBRATION',
  UPGRADE: 'UPGRADE',
  INSTALLATION: 'INSTALLATION',
  DECOMMISSION: 'DECOMMISSION'
} as const;

// Work Order Priority Constants  
export const WORK_ORDER_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
  EMERGENCY: 'EMERGENCY'
} as const;

// Maintenance Type Constants
export const MAINTENANCE_TYPE = {
  PREVENTIVE: 'PREVENTIVE',
  PREDICTIVE: 'PREDICTIVE',
  CONDITION_BASED: 'CONDITION_BASED',
  TIME_BASED: 'TIME_BASED',
  USAGE_BASED: 'USAGE_BASED'
} as const;

// Asset Audit Action Constants
export const ASSET_AUDIT_ACTION = {
  ASSET_CREATED: 'ASSET_CREATED',
  ASSET_UPDATED: 'ASSET_UPDATED',
  ASSET_DELETED: 'ASSET_DELETED',
  ASSET_MOVED: 'ASSET_MOVED',
  ASSET_TRANSFERRED: 'ASSET_TRANSFERRED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  CONDITION_CHANGED: 'CONDITION_CHANGED',
  MAINTENANCE_SCHEDULED: 'MAINTENANCE_SCHEDULED',
  MAINTENANCE_COMPLETED: 'MAINTENANCE_COMPLETED',
  DEPRECIATION_CALCULATED: 'DEPRECIATION_CALCULATED',
  VALUE_ADJUSTED: 'VALUE_ADJUSTED',
  ASSET_CLONED: 'ASSET_CLONED'
} as const;

// Default Configuration Values
export const DEFAULT_CONFIG = {
  // Pagination defaults
  DEFAULT_PAGE_SIZE: 50,
  MAX_PAGE_SIZE: 1000,
  
  // Bulk operation limits
  MAX_BULK_CREATE_SIZE: 1000,
  MAX_BULK_UPDATE_SIZE: 500,
  DEFAULT_BATCH_SIZE: 100,
  
  // Maintenance scheduling defaults
  DEFAULT_MAINTENANCE_INTERVAL_DAYS: 90,
  DEFAULT_WARRANTY_ALERT_DAYS: 30,
  DEFAULT_OVERDUE_THRESHOLD_DAYS: 7,
  
  // Depreciation defaults
  DEFAULT_USEFUL_LIFE_YEARS: 10,
  DEFAULT_SALVAGE_VALUE_PERCENTAGE: 0.1,
  DEFAULT_DEPRECIATION_METHOD: 'STRAIGHT_LINE',
  
  // File limits
  MAX_IMPORT_FILE_SIZE_MB: 50,
  MAX_EXPORT_RECORDS: 100000,
  
  // Asset tag configuration
  MIN_ASSET_TAG_LENGTH: 3,
  MAX_ASSET_TAG_LENGTH: 50,
  ASSET_TAG_PATTERN: /^[A-Z0-9\-_]+$/i,
  
  // Description limits
  MAX_ASSET_NAME_LENGTH: 200,
  MAX_DESCRIPTION_LENGTH: 1000,
  MAX_NOTES_LENGTH: 2000,
  
  // Financial limits
  MAX_ASSET_VALUE: 99999999.99,
  MIN_ASSET_VALUE: 0,
  
  // Search and filtering
  MAX_SEARCH_RESULTS: 10000,
  DEFAULT_SORT_FIELD: 'assetName',
  DEFAULT_SORT_ORDER: 'asc',
  
  // Cache configuration
  ASSET_CACHE_TTL_SECONDS: 300, // 5 minutes
  METRICS_CACHE_TTL_SECONDS: 600, // 10 minutes
  
  // Retry configuration
  MAX_RETRY_ATTEMPTS: 3,
  RETRY_DELAY_MS: 1000,
  
  // Notification delays
  NOTIFICATION_BATCH_DELAY_MS: 100,
  ESCALATION_DELAY_MINUTES: 60,
} as const;