/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface BaseEntity {
  id: string
  organizationId: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  version: number
  isActive: boolean
  metadata?: Record<string, string>
}

export interface AssetLifecycleData {
  baseEntity: BaseEntity
  assetId: string
  depreciationMethod: string
  usefulLife: number
  salvageValue: number
  purchasePrice: number
  purchaseDate: Date
  replacementCost?: number
  replacementDate?: Date
  disposalMethod?: string
  disposalValue?: number
}

export interface DepreciationCalculation {
  year: number
  startingValue: number
  depreciationAmount: number
  accumulatedDepreciation: number
  endingValue: number
  rate?: number
}

export interface ReplacementPlan {
  assetId: string
  assetName: string
  currentAge: number
  remainingUsefulLife: number
  currentCondition: string
  estimatedReplacementCost: number
  recommendedReplacementDate: Date
  priority: string
  justification: string
  budgetImpact: number
  riskOfFailure: number
  businessImpact: string
  alternativeOptions: Array<string>
}

export interface StandardResponse<T> {
  success: boolean
  data?: T
  error?: ErrorResponse
  metadata?: ResponseMetadata
}

export interface ErrorResponse {
  code: string
  message: string
  details?: Record<string, string>
}

export interface ResponseMetadata {
  timestamp: Date
  requestId: string
  executionTime: number
  apiVersion: string
}

export class AssetLifecycleService {
  constructor()
  calculateStraightLineDepreciation(purchasePrice: number, salvageValue: number, usefulLife: number, currentYear: number): DepreciationCalculation
  calculateDecliningBalanceDepreciation(purchasePrice: number, salvageValue: number, usefulLife: number, currentYear: number, accelerationFactor: number): DepreciationCalculation
  generateReplacementPlan(assetId: string, assetName: string, purchaseDate: Date, usefulLife: number, currentCondition: string, replacementCost: number): Promise<ReplacementPlan>
  validateAssetLifecycleData(data: AssetLifecycleData): boolean
  calculateTotalCostOfOwnership(purchasePrice: number, annualMaintenanceCost: number, annualOperatingCost: number, usefulLife: number, disposalCost: number, salvageValue: number): Promise<number>
}

export function init(): string