/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Base entity structure following the universal data standard */
export interface BaseEntity {
  id: string
  organizationId: string
  createdAt: string
  updatedAt: string
  createdBy: string
  updatedBy: string
  version: number
  isActive: boolean
  metadata?: Record<string, string>
}
/** Standard response structure */
export interface StandardResponse {
  success: boolean
  data?: string
  error?: ErrorResponse
  metadata?: ResponseMetadata
}
export interface ErrorResponse {
  code: string
  message: string
  details?: Record<string, string>
}
export interface ResponseMetadata {
  timestamp: string
  requestId: string
  executionTime: number
  apiVersion: string
}
/** Initialize the module */
export declare function init(): string
/** Preventive maintenance scheduling and management */
export declare class PreventiveMaintenanceServiceService {
  constructor()
  /** Initialize the service */
  initialize(config: Record<string, string>): boolean
  /** Health check for the service */
  healthCheck(): string
  /** Get service information */
  getServiceInfo(): Record<string, string>
}
