/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface BaseEntity {
  id: string
  organizationId: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  version: number
  isActive: boolean
  metadata?: Record<string, string>
}

export interface StandardResponse<T> {
  success: boolean
  data?: T
  error?: ErrorResponse
  metadata?: ResponseMetadata
}

export interface ErrorResponse {
  code: string
  message: string
  details?: Record<string, string>
}

export interface ResponseMetadata {
  timestamp: Date
  requestId: string
  executionTime: number
  apiVersion: string
}

export class ComplianceService {
  constructor()
  initialize(config: Record<string, string>): Promise<boolean>
  healthCheck(): string
  getServiceInfo(): Record<string, string>
}

export function init(): string